### ISSUE TITLE
Add remark regarding `noAccessor` and `reflect` to documentation

### ISSUE THREAD

**Issue by jun-sheaf** [lit/lit-element#1095]
## Description
- Who wants the functionality
New, advanced users.
- What it is they want
A remark regarding the relationship between `noAccessor` and `reflect`. In particular, if `noAccessor` is `true`, then `reflect` no longer applies and any manually written setters must manually set the attribute to properly reflect.
- Why they want it
This could be obvious to those aware of how accessors and overrides work in JavaScript, but it is certainly non-trivial for those that blackbox their understanding of accessors.
- Functional description of task/subtask
Add a small remark regarding the 'What it is they want' description laid out here.

## Acceptance criteria
A visible statement on the `Properties` documentation page regarding the 'What it is they want' description.

**Comment by arthurevans** [comment]
Hi. Can you clarify what you're trying to achieve with `noAccessor`? 

If you're just adding a custom accessor, you don't need to add `noAccessor: true`. You do need to manually call `requestUpdate` if you want the component to reflect the property, update templates, etc. The requirement is mentioned here:

https://lit-element.polymer-project.org/guide/properties#accessors-custom

This section could be improved by clarifying what calling `requestUpdate` does.

Setting `noAccessor: true` is more rarely used, and it's only needed if:

1) You you have a superclass, A, that defines a custom accessor for a property, P, and 
2) You have a subclass, B, that overrides some of the property options for property P, but does not define a new accessor.

https://lit-element.polymer-project.org/guide/properties#accessors-noaccessor

In this case, property P should reflect as long as its `reflect` option is true and the superclass accessor calls `requestUpdate`.

This section could be a little clearer about the specific use case. It could also mention that the superclass accessor must call `requestUpdate`, just like any custom accessor.

**Comment by jun-sheaf** [comment]
My personal use case is your point (1), however I do _not_ call 'requestUpdate' since I do not need rerendering. Judging from your comment, it seems 'requestUpdate' does some undocumented features such as reflecting attributes! Unless I am misunderstanding something here...

**Comment by arthurevans** [comment]
You're correct. Reflecting attributes is part of the whole update lifecycle. This is mentioned in the docs for update, for example:

https://lit-element.polymer-project.org/guide/lifecycle#update

Also in "What happens when properties change." 

However, I think we could make it clearer in several places:

- In the introduction to the "Lifecycle" chapter, explicitly mention reflecting attributes as part of the update process (currently it just says "process properties and attributes" which is vague and unhelpful).
- In the reflected attributes section of this guide, mention that attributes are reflected as part of the update cycle.
- In the custom accessors section of the guide, add a sentence explaining why you need to call requestUpdate. (To cause the element to rerender, update any reflected attributes, and run the callbacks related to the update cycle.)

**Comment by jun-sheaf** [comment]
These revisions sound optimal 👍

**Comment by kevinpschaaf** [comment]
Covered under https://lit.dev/docs/components/properties/#property-options now.
