### ISSUE TITLE
[docs] update terminology in docs per discussion below

### ISSUE THREAD

**Issue by ghost** [lit/lit-element#406]
Clarify some technical details of the terminology used in method names, readme, comments, docs, etc. Maybe do a glossary, idk

Make sure the terms are used correctly & consistently in the docs and that users will know what they mean when they are used

Need to define these terms so I can understand & use them properly:

 **term** | **definition** (my best guess) 
--------|------------
render | put newest values into DOM elements in the render root 
update (to update an element) | perform property/attribute effects & render DOM changes
updated | element's lifecycle has run from beginning to end & updatePromise has resolved (but element has not necessarily been rendered? e.g firstUpdated... **confused about this one**) 
request an update | enqueue something to kick off the rest of the update lifecycle
schedule an update | after update has been requested, create a promise that will, when resolved, kick off the code to perform the update
connected | Custom element has been appended into another element that is in `window.document`
register a property | add it to LitElement data system so property update stuff will be run on it according to any options in its declaration
observe a property | make it so that setting the property will start the LitElement lifecycle checks for whether an update is required
finalized |  element is finalized when all its property accessors are created && all its (subclasses'? superclasses'?) property accessors are created
instance properties | properties on an actual element vs on its class? 
initialize | initialize a property: give it its first value; initialize an element: create a render root and save instance property values (from where? e.g. markup? anywhere else?)
create an element's template | ??? initialize DOM children based on the html in render() ?
define an element's template | implement `render()` & specify some html that will be appended to the element's shadow root or some other specified node depending on where the render root is

**Comment by katejeffreys** [comment]
@justinfagnani @arthurevans @sorvell @keanulee @kevinpschaaf any ideas for corrections on these definitions would be great. Once they're technically correct I can improve the wording

**Comment by bennypowers** [comment]
I made a few revisions for your consideration.

term | definition
-- | --
`render` | add or modify DOM nodes based on template and state.
`update` (to update an element) | perform property/attribute effects then render DOM changes.
`updated` | element's lifecycle has run from beginning to end. `updatePromise` has resolved (but element has not necessarily been rendered? e.g firstUpdated... confused about this one).
request an update | enqueue the update lifecycle to run again, whether or not state has changed.
schedule an update | after update has been requested, create a promise that will, when resolved, perform the update.
connected | Custom element has been appended into another element that is in window.document.
register a property | add it to LitElement data system so property update stuff will be run on it according to any options in its declaration.
observe a property | cause setting the property to start the LitElement property effects (i.e. lifecycle checks).
`finalized` | element is finalized when all its property accessors are created and all its property accessors are created.
instance properties | properties on an instance of an element, as opposed to static properties which are defined on the class.
initialize (property) | set a property's initial value.
initialize (element) | create a render root and set instance property values (based on constructor, class fields, decorators, and DOM properties).
define an element's template | implement render(). i.e. specify the DOM tree that will be appended to the element's render root.
render root | the node at which the element's template is or will be appended. By default, this is the element's open shadow root.

I'm not sure what the intended difference is between "create" and "define" template. It seems to me that the docs should be revised to clarify this distinction, rather than introducing a new glossary term.

**Comment by justinfagnani** [comment]
"create" is a pretty ambiguous term when dealing with things like classes and templates. In both cases you have the definition (the class or template), and one or more instances. "Define" or "declare" vs "instantiate" is clearer. In the template case "clone" is probably better than "instantiate".

In this case though, we have a specialized term for "instantiate"/"clone": "render". It's better because it covers the initial rendering of a template, and subsequent updates.

Otherwise, here's my take on the terms....

 **term** | **definition**
--------|------------
render | Cause the DOM described by a template to be created or updated with a specific set of values.
update (to update an element) | Reconcile an element to reflect its current state. This may including rendering DOM that depends on the state.
updated() (the method) | Callback method called at the end of the element's update lifecycle, specifically after update() has finished. (In LitElement update() does the rendering work).
request an update | Enqueue a task to execute the update lifecycle. If an update task is already enqueued, an additional task is _not_ enqueued.
schedule an update | Does the actual update task enqueuing and execution. Returns a Promise that resolves when the update task is complete.
connected | The element is connected to a parent element that is also connected, meaning that every ancestor element is connected up to the Socument.
Define/declare a property | Generates a getter/setter pair (accessor) whose setter requests an update. Also associated some metadata with a property used in the update lifecycle, like the associated attribute name, attribute type, etc.
observe a property | (redefining this term. Usually when people ask "how do I observe a property?" they mean how do they run their own code when a property changes. UpdatingElement already observes declared properties). Have code run when a property changes.
finalized | An element _class_ is finalized when all its property accessors are created, including accessors on the classes superclass.
instance properties | Can mean two things: 1) Properties on an actual object instance vs on its prototype. 2) Properties associated with an object instance, whether or not on the object or its prototype chain, vs static properties on the class.
initialize | initialize a property: give it its first value
initialize an element | Perform all sorts of initialization tasks. Create a render root, initialize property values; add event listeners, load external dependencies, etc...
define an element's template | implement `render()` & specify some html that will be appended to the element's shadow root or some other specified node depending on where the render root is
instantiate an element's template | _see render_

**Comment by kevinpschaaf** [comment]
Given that the docs have been almost completely rewritten, at this point rather than adding a glossary page, I think we'd rather identify existing areas of the new docs that use jargony/not-previously-defined words and then reconsider if a page like this would be helpful, so we'll close this in preference of issues specifically pointing out such areas.
