### ISSUE TITLE
CSS rule with content and CSS entity reference results to an undefined stylesheet

### ISSUE THREAD

**Issue by drdreo** [lit/lit-element#637]
### Description
When using the styles getter inside a LitElement and having a CSS rule that includes some special character escaping results in the whole StyleSheet to be undefined.
Removing the special character rule makes it work again.

Example css:
```css
 static get styles() {
    return [css` 
      div {background-color:#ff0}
      div::before {content:"\2014"}
    `];
  }
```
Is it possible to get that supported inside LitElements?

#### Live Demo
https://stackblitz.com/edit/lit-element-example-5fv9er

#### Steps to Reproduce
1. Run  the app
2. Remove the `div::before{content:"\2014"}` CSS rule
3. StyleSheet works again

#### Expected Results
It should show the content before every div.

#### Actual Results
StyleSheet is undefined. Actually stored the css rules in a variable to see what happens. 
Output:
```json
{
  "_styleSheet": {}
}
```

### Browsers Affected
- [x] Chrome

### Versions
-  "lit-element": "^2.0.0-rc.5",

**Comment by Mottie** [comment]
You need to escape the backslash `content:"\\2014"`.

**Comment by drdreo** [comment]
Which is 
- cumbersome for designers that are used to write correct CSS
- not that easy when loading the CSS from a file which doesn't escape backslashes
- a workaround not a solution (other tools can handle unescaped CSS just fine)

I have tried to adopt a webpack-loader that grabs the CSS from a file and generate the needed lit css syntax. Although, search-replacing backslashes is not easy in JS, at least i haven't found a way to do that programmatically.

**Comment by kuka-radovan** [comment]
I am facing this problem with 3rd party css... so sadly I have no chance to escape anything.

**Comment by kuka-radovan** [comment]
I tried to figure out what is going on on lit-element side and it looks like it goes deeper and this behaviour is caused by tagged templated string. More over, it looks like this is default behaviour of javascript engine and templated string behaves the same way. So the only solution for now is escape slashes in source code.

**Comment by ryangroth5** [comment]
I belive this is a side effect. 

The documentation needs to be spelled out on this "problem". I also think that there should maybe be a special template literal for a raw file (e.g. fileCSS) where you process the .raw (post-interpolated) template literals. 

I don't know how common this is (https://tc39.github.io/proposal-template-literal-revision/) but it seems to be present in the browsers I am testing. 

I was able to solve this problem with a patch to lit-element and using the unsafeCSS, you could similarly check the cssText for undefined in the css template tag and apply the raw in that case as well

-- 


```
index cea2875..7920009 100644
--- a/node_modules/lit-element/lib/css-tag.js
+++ b/node_modules/lit-element/lib/css-tag.js
@@ -46,7 +46,7 @@ export class CSSResult {
  * this with trusted input.
  */
 export const unsafeCSS = (value) => {
-    return new CSSResult(String(value), constructionToken);
+    return new CSSResult(String(value) || String(value.raw), constructionToken);
 };
 const textFromCSSResult = (value) => {
     if (value instanceof CSSResult) {
diff --git a/node_modules/lit-element/src/lib/css-tag.ts b/node_modules/lit-element/src/lib/css-tag.ts
index e508be3..5502c78 100644
--- a/node_modules/lit-element/src/lib/css-tag.ts
+++ b/node_modules/lit-element/src/lib/css-tag.ts
@@ -57,7 +57,7 @@ export class CSSResult {
  * this with trusted input.
  */
 export const unsafeCSS = (value: unknown) => {
-  return new CSSResult(String(value), constructionToken);
+  return new CSSResult(String(value) || String(value.raw), constructionToken);
 };

 const textFromCSSResult = (value: CSSResult) => {
```

**Comment by hyperpress** [comment]
This most likely a failure on updating the lit-element style doc. There is
PR awaiting merge at:

https://github.com/Polymer/lit-element/pull/600/commits/64985b86d359ce6b668adf00bd6586bef9e977a7

Please refer to this for guidance for now.

**Comment by ryangroth5** [comment]
sort of...the issue is in the real world you want a build process where you can do something like this:

import css from '/some/commerical/library/not/under/my/control.css' 

as part of your build process but it is buggered up with css unicode escape sequences like 
```css
ul::before
{
content: \2022
}
```

and you can't really do much about preprocessing it before it becomes a template literal, when it does it breaks because the template processing function (like css in css-tag.js) gets "undefined" as the template result.  This same function gets strings.raw as well. The right way might be to check if strings[0] is undefined and if strings.raw is defined it should process that instead. 

The author of the ticket's example is also valid and is solved equally where the css template function will accept either the template interpolation OR the raw value if the template interpolation is not available. 

If you don't accept a code change, then I would at least document that unicode escape sequences can break ES2016 template strings and the result will import correctly as a css template literal .

I think my example (above) probably should involve css and not unsafeCSS, but essentially the same fix

**Comment by graynorton** [comment]
Looks like this is just a gotcha we need to add to the docs.

**Comment by kevinpschaaf** [comment]
Caveats around escaping CSS in template literals is now covered in https://lit.dev/docs/components/styles/#using-unicode-escapes-in-styles.
